version: "3"

services: 
    app:
        container_name: rampoo-hello
        restart: on-failure
        build: 
            context: .
        ports: 
            - 3000:3000
            - 3002:3002
        volumes:
            - .:/app